server:
  port: 9898

spring:
  application:
    name: test-security-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #mysql驱动包
    driver-class-name: org.gjt.mm.mysql.Driver    #当前数据源操作类型
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    show-sql: true #默认false,在日hi里显示执行的sql语句
    database: mysql
    hibernate:
      ddl-auto: update
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhang.security.entities
# mybatis打印sql
logging:
  level:
    com.zhang.security.dao.mapper : debug